name: artbyron
favicon: null
layout_spectrum: 0.2955444888211787
typography_spectrum: 0.5845988148357719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3242267360910773
  lightness: 0.8249031931627542
  saturation: 0.8583595699165016
  rhythmicContrast: 0.32541025476530194
purpose: []
